### ISSUE TITLE
Dangerous sudo

### ISSUE THREAD

**Issue by bgmeulem** [Shringe/dunst-media-control#1]
To fetch brightness information, you use `sudo light`. Some systems have a timeout in place for sudo requests (I suppose to prevent bruteforcing), and lock out the user of sudo if the requests are too quick. Tapping brightness controls tends to be quick, and I locked myself out of my own device a handful of times before discovering this was the issue. 

So I propose it would make sense to have brightness controls that don't require `sudo`? I adapted your script to use `brightnessctl`(https://github.com/Hummer12007/brightnessctl) and that works like a charm.

Absolutely lovely script for the rest though, works very well!

**Comment by Shringe** [comment]
I don't actually have controllable brightness on my display to test this; the brightness control came from the original project. Can I see the changes you made to the script to work with `brightnessctl`?
